//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.10 at 04:39:53 PM BST 
//


package com.coriant.testng.robot.datamodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for statistics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="statistics"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="total" type="{}stats"/&gt;
 *         &lt;element name="tag" type="{}stats"/&gt;
 *         &lt;element name="suite" type="{}stats"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "statistics", propOrder = {

})
public class Statistics {

    @XmlElement(required = true)
    protected Stats total;
    @XmlElement(required = true)
    protected Stats tag;
    @XmlElement(required = true)
    protected Stats suite;

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link Stats }
     *     
     */
    public Stats getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stats }
     *     
     */
    public void setTotal(Stats value) {
        this.total = value;
    }

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link Stats }
     *     
     */
    public Stats getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stats }
     *     
     */
    public void setTag(Stats value) {
        this.tag = value;
    }

    /**
     * Gets the value of the suite property.
     * 
     * @return
     *     possible object is
     *     {@link Stats }
     *     
     */
    public Stats getSuite() {
        return suite;
    }

    /**
     * Sets the value of the suite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stats }
     *     
     */
    public void setSuite(Stats value) {
        this.suite = value;
    }

}
