//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.10 at 04:39:53 PM BST 
//


package com.coriant.testng.robot.datamodel;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for status complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="status"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute ref="{}status use="required""/&gt;
 *       &lt;attribute name="endtime" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="elapsedtime" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute ref="{}critical"/&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "status", propOrder = {
        "value"
})
public class Status {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "status", required = true)
    protected String status;
    @XmlAttribute(name = "endtime")
    protected String endtime;
    @XmlAttribute(name = "starttime")
    protected String starttime;
    @XmlAttribute(name = "elapsedtime")
    protected String elapsedtime;
    @XmlAttribute(name = "critical")
    protected String critical = "yes";

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStatus(String value) {
        if (status == null) {
            status = value;
        } else if (!status.isEmpty() && !status.equals("FAIL")) {
            status = value;
        }
    }

    public void forceStatus(String value) {
        status = value;
    }

    /**
     * Gets the value of the endtime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * Sets the value of the endtime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEndtime(String value) {
        this.endtime = value;
    }

    /**
     * Gets the value of the starttime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * Sets the value of the starttime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStarttime(String value) {
        this.starttime = value;
    }

    /**
     * Gets the value of the elapsedtime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getElapsedtime() {
        return elapsedtime;
    }

    /**
     * Sets the value of the elapsedtime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setElapsedtime(String value) {
        this.elapsedtime = value;
    }

    /**
     * Gets the value of the critical property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCritical() {
        return critical;
    }

    /**
     * Sets the value of the critical property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCritical(String value) {
        this.critical = value;
    }

}
